export enum BussinessActionTypes {
  SET_RESULTS = 'SET_RESULTS',
  SET_RESULTS_MAP = 'SET_RESULTS_MAP',
  SET_LOADING = 'SET_LOADING',
  SET_REVIEWS_PENDING = 'SET_REVIEWS_PENDING',
  SET_BUSINESS = 'SET_BUSINESS',
  SET_REVIEWS = 'SET_REVIEWS',
  SELECTED_PENDING = 'SELECTED_PENDING',
  REQUEST_ERROR = 'REQUEST_ERROR',
  SET_PARAMS = 'SET_PARAMS'
}
